name: My First Workflow
on:
  push: 
    branches:
      - "release"
jobs:
  echo_the_date:
    runs-on: ubuntu-latest
    steps:
    - name: echo the date
      run: echo "The current time and date is $(date)"
    - name: echo the current branch
      run: echo ${{github.ref_name}}

  build_and_deploy:
    runs-on: ubuntu-latest
    steps:

    #https://github.com/marketplace/actions/checkout
    - name: Checkout the source
      uses: actions/checkout@v3

    #https://github.com/marketplace/actions/build-and-push-docker-images
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    #https://github.com/marketplace/actions/docker-login#docker-hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: user/app:latest

    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK